# site settings
title: Liquid Perfection 
subtitle: 
email: liquidperfectionjax@gmail.com
description: <!-- Form --> <h3>REQUEST A FREE ESTIMATE TODAY!</h3> <br /> <br /><p></p> <form method="post" action="#"> <div class="row uniform"> <div class="6u 12u$(xsmall)"> <input type="text" name="name" id="name" value="" placeholder="Name" /> </div> <div class="6u$ 12u$(xsmall)"> <input type="email" name="email" id="email" value="" placeholder="Email" /> </div> <div class="6u$ 12u$(xsmall)"> <input type="tel" name="phone" id="phone" value="" placeholder="Phone" /> </div> <!-- Break --> <div class="12u$"> <div class="select-wrapper"> <select name="flooring" id="flooring"> <option value="">- Flooring Type -</option> <option value="Flake">Flake</option> <option value="Reflector">Reflector</option> <option value="Custom">Custom</option> </select> </div> </div> <!-- Break --> <div class="6u$ 12u$(small)"> <input type="checkbox" id="demo-human" name="demo-human" checked> <label for="demo-human">I am a human</label> </div> <!-- Break --> <div class="12u$"> <ul class="actions"> <li><input type="submit" value="Go!" class="special" /></li> <li><input type="reset" value="Reset" /></li> </ul> </div> </div> </form>
baseurl: "/liquidperfectionjax" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 3051 Waters View Circle
city: Orange Park
state: FL
zip_code: 32073
country: United States of America
phone: (904) 329-5312

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/Liquid-Perfection-1374511976188884/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
